services:
  fastapi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    env_file:
      - ".env"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: