"""year to int

Revision ID: 07212d9cdd09
Revises: 98cf2a609604
Create Date: 2024-10-10 01:21:40.670220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07212d9cdd09'
down_revision: Union[str, None] = '98cf2a609604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('car_model', 'motorization',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=1),
               existing_nullable=False)
    op.alter_column('manufacturer', 'foundation_year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manufacturer', 'foundation_year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('car_model', 'motorization',
               existing_type=sa.Float(precision=1),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
