"""add cascade for car models

Revision ID: f969f36fa978
Revises: 046ddb9dc61c
Create Date: 2024-10-17 01:14:22.227760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f969f36fa978'
down_revision: Union[str, None] = '046ddb9dc61c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('car_model_manufacturer_id_fkey', 'car_model', type_='foreignkey')
    op.create_foreign_key(None, 'car_model', 'manufacturer', ['manufacturer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_model', type_='foreignkey')
    op.create_foreign_key('car_model_manufacturer_id_fkey', 'car_model', 'manufacturer', ['manufacturer_id'], ['id'])
    # ### end Alembic commands ###
